// AUTO-GENERATED by scripts/build-products.mjs — do not edit.
export const categories: { name: string; icon: string }[] = [
  {
    "name": "Audio",
    "icon": "Headphones"
  },
  {
    "name": "Celulares",
    "icon": "Smartphone"
  },
  {
    "name": "Accesorios",
    "icon": "Briefcase"
  },
  {
    "name": "Electrónica",
    "icon": "Smartphone"
  },
  {
    "name": "Gaming",
    "icon": "Gamepad2"
  },
  {
    "name": "Smartwatch",
    "icon": "Briefcase"
  },
  {
    "name": "Televisores",
    "icon": "Tv"
  },
  {
    "name": "Cámaras",
    "icon": "Camera"
  },
  {
    "name": "Computación",
    "icon": "Laptop"
  }
];
